### ISSUE TITLE
数据集请求

### ISSUE THREAD

**Issue by wzy2022y** [summitgao/NNCNet#1]
您好，您可以提供一下您论文中用到的数据集吗？不胜感激，期待您的回复。

**Comment by summitgao** [comment]
不好意思，刚看到。。。你是需要哪个数据集呢？

**Comment by wzy2022y** [comment]
您好，十分感谢谢您的回复，之前我拜读了您的文章 “Nearest Neighbor-Based Contrastive Learning for Hyperspectral and LiDAR Data Classification”，但在运行程序时遇到了错误，可否提供 Houston2018 数据集：   ，我在使用您提供的其他两个公共数据集时（非.npy格式）也遇到了数据集加载错误，可否也提供muufl和Houston2013数据集，万分感谢，期待您的回复！！！











在 2023-08-10 01:14:34，"Feng Gao" ***@***.***> 写道：

不好意思，刚看到。。。你是需要哪个数据集呢？

**Comment by yuanzhishange** [comment]
您好，十分感谢谢您的回复，之前我拜读了您的文章 “Nearest Neighbor-Based Contrastive Learning for Hyperspectral and LiDAR Data Classification”，但在运行程序时遇到了错误，可否提供 Houston2018 数据集：   ，我在使用您提供的其他两个公共数据集时（非.npy格式）也遇到了数据集加载错误，可否也提供muufl和Houston2013数据集，万分感谢，期待您的回复！！！

**Comment by summitgao** [comment]
> 您好，十分感谢谢您的回复，之前我拜读了您的文章 “Nearest Neighbor-Based Contrastive Learning for Hyperspectral and LiDAR Data Classification”，但在运行程序时遇到了错误，可否提供 Houston2018 数据集： ，我在使用您提供的其他两个公共数据集时（非.npy格式）也遇到了数据集加载错误，可否也提供muufl和Houston2013数据集，万分感谢，期待您的回复！！！

数据集是我们在网上下载的，需要的话可以邮件联系 gaofeng@ouc.edu.cn，我抄送给组里学生转发给你
