### ISSUE TITLE
请问model里的两个类NET1和NET2的作用？

### ISSUE THREAD

**Issue by whper07** [summitgao/NNCNet#2]
我在阅读了您的model.py代码后，并不理解net1和net2的作用？并且在pretrain.py里NNCNET调用的是NET1且save模型，而在train里如何做到采用NET2却loadNET1的模型呢？，

**Comment by summitgao** [comment]
感谢关注，我不负责代码，我问问

**Comment by Arsene-W** [comment]
Net1 是预训练模型，而 Net2 是正式训练模型。这两个模型的区别主要在于最后的输出部分。在将预训练模型 (Net1) 导入到训练流程时，我们只加载两个模型共有的 'backbone' 特征提取部分，以此来保留预训练过程中得到的参数。

**Comment by summitgao** [comment]
> Net1 是预训练模型，而 Net2 是正式训练模型。这两个模型的区别主要在于最后的输出部分。在将预训练模型 (Net1) 导入到训练流程时，我们只加载两个模型共有的 'backbone' 特征提取部分，以此来保留预训练过程中得到的参数。

感谢王猛的解答！
